services:
    html-preview-online:
        image: ghcr.io/jwygithub/html-preview-online
        ports:
            - '9300:3000'
        volumes:
            - ./public:/app/public:cached
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - PORT=3000
            - NEXT_PUBLIC_BASE_PATH=preview
        healthcheck:
            test: ['CMD', 'wget', '--spider', 'http://localhost:3000/preview/api/preview-page']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 15s

volumes:
    pnpm-store:
        name: pnpm-store

