services:
    html-preview-online:
        image: html-preview-online:latest
        ports:
            - '9300:3000'
        volumes:
            - ./public:/app/public:cached
            - pnpm-store:/root/.pnpm-store
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - PORT=3000
            - BASE_PATH=preview
        healthcheck:
            test: ['CMD', 'wget', '--spider', 'http://localhost:3000/preview']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 15s

volumes:
    pnpm-store:
        name: pnpm-store

